baseurl = "https://blog.opramachine.com"
DefaultContentLanguage = "en"
title = "OPRAmachine Blog"
theme = "hugo-theme-bleak"
metaDataFormat = "yaml"
disqus = "blog-opramachine-com"
#googleAnalytics = "XXX"

[params]
  Subtitle = "The official blog of New Jersey's government transparency platform."
  logo = "img/favicon.png"
  cover = "img/homepage-background.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[params.author]
  name = "OPRAmachine"
  website = "https://gavinrozzi.com"
  facebook = "opramachine"
  github = "gavinrozzi"
  image = "img/favicon.jpg"
  twitter = "opramachine"
  youtube = "channel/UC6gZYhaHQsnjHkngEWEF2Aw" # or channel/channelname

[[menu.main]]
    name = "Documentation"
    url = "https://docs.opramachine.com/"
    weight = 1

[[menu.main]]
    name = "Request Public Records"
    url = "https://opramachine.com/select_authority"
    weight = 2

[[menu.main]]
    name = "NJ OPRA Facebook Group"
    url = "https://www.facebook.com/groups/njopra"
    weight = 3
